# Generated by Django 2.0.5 on 2018-05-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_viewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='usr',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='frl',
        ),
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.CharField(default='test', max_length=128, unique=True),
        ),
    ]
